### ISSUE TITLE
Triangle and Interleave data question.

### ISSUE THREAD

**Issue by nanjizal** [rainyt/openfl-glsl#1]
Does this library allow drawing with Triangles and interleave data ( Float32Array of xyz,rgba,uv ). I presume this is not possible since OpenFL uses quads by default?
Does this work with WebGL as well ?

Essentially I wanted to run some of my triangle drawing code in OpenFL, I have made some basic prototypes in Lime, nme ( and webgl textures as well ), but integration with OpenFL might be more complex.

Specifically I wanted to run these shaders within OpenFL, do you think this is feasible.. any hints..

```haxe
inline
var vertexString0: String =
    'attribute vec3 vertexPosition;' +
    'attribute vec4 vertexColor;' +
    'varying vec4 vcol;' +
    'void main(void) {' +
        ' gl_Position = vec4(vertexPosition, 1.0);'+
        ' vcol = vertexColor;' +
    '}';
inline
var vertexString1: String =
    'attribute vec3 vertexPosition;' +
    'attribute vec4 vertexColor;' +
    'uniform mat4 modelViewProjection;' +
    'varying vec4 vcol;' +
    'void main(void) {' +
        ' gl_Position = modelViewProjection * vec4( vertexPosition, 1.0);' +
        ' vcol = vertexColor;' +
    '}';
    
inline
var fragmentString0: String =
    'precision mediump float;'+
    'varying vec4 vcol;' +
    'void main(void) {' +
        ' gl_FragColor = vcol;' +
    '}';
    
inline
var textureVertexString1: String =
    'attribute vec3 vertexPosition;' +
    'attribute vec4 vertexColor;' +
    'attribute vec2 vertexTexture;' +

    'varying vec4 vcol;' +
    'varying vec2 vtexture;' +
    
    'uniform mat3 uvTransform;' +
    
    'void main(void) {' +
        ' gl_Position = vec4( vertexPosition, 1.0);' +
        //' vtexture = vec2( vertexTexture.x , 1.-vertexTexture.y );' +
        ' vec3 texChange = uvTransform * vec3(vertexTexture, 1.0);' + 
        ' vtexture = vec2( texChange );' +
        ' vcol = vertexColor;' +
    '}';
inline
var textureVertexString2: String =
    'attribute vec3 vertexPosition;' +
    'attribute vec4 vertexColor;' +
    'attribute vec2 vertexTexture;' +
    
    'varying vec4 vcol;' +
    'varying vec2 vtexture;' +
    
    'uniform mat3 uvTransform;' +
    
    'uniform mat4 modelViewProjection;' +
    
    'void main(void) {' +
        ' gl_Position = modelViewProjection * vec4( vertexPosition, 1.0);' +
        //' vtexture = vec2( vertexTexture.x , 1.-vertexTexture.y );' +
        ' vec3 texChange = uvTransform * vec3(vertexTexture, 1.0);' + 
        ' vtexture = vec2( texChange );' +
        ' vcol = vertexColor;' +
    '}';
inline
var textureFragmentString: String =
    'precision mediump float;' +
    'precision mediump int;' +
    
    'varying vec4 vcol;' +
    'varying vec2 vtexture;' +
    
    'uniform sampler2D uImage0;' +
    'uniform vec4 bgColor;' +
    'void main(void) {' +
    'if (vtexture.x < 0.0 || vtexture.y < 0.0 || vtexture.x > 1.0 || vtexture.y > 1.0) {' +
        ' gl_FragColor = bgColor; '+
    '} else {'+
        'vec4 texcolor = texture2D( uImage0, vec2( vtexture.s, vtexture.t ) ).rgba * vcol;' +
        'texcolor.rgb *= vcol.a; ' + 
        'if( texcolor.a < 1. ){' +
            'texcolor = mix( bgColor, texcolor, texcolor.a ); '+
            '}'+
        'gl_FragColor = texcolor;'+
        '}'+
    '}';
    
  ```

**Comment by rainyt** [comment]
Use: https://github.com/haxiomic/vector-math
Float32Array of xyz, rgba, uv and other data will be implemented by the vector-math library, and openfl-glsl is responsible for translating Haxe to GLSL, so I think it can solve most of the problems.

At the same time, I am also learning GLSL and have also written some examples:
https://github.com/rainyt/openfl-glsl-samples

**Comment by rainyt** [comment]
If you encounter translation problems, you can create a problem and let me know.

**Comment by rainyt** [comment]
GLSL Examples:
```haxe
package zygame.shader;

import glsl.OpenFLShader;
import VectorMath;

/**
 * 流光效果渲染
 */
@:debug
class FluxaySuperShader extends OpenFLShader {
	@:uniform public var speed:Float;

	@:precision("highp float")
	@:define("TAU 6.12")
	@:define("MAX_ITER 5")
	override function fragment() {
		super.fragment();
		var time:Float = speed * 0.5 + 5;
		// uv should be the 0-1 uv of texture...
		var uv:Vec2 = gl_openfl_TextureCoordv.xy;
		var p:Vec2 = mod(uv * TAU, TAU) - 250.0;
		var i:Vec2 = vec2(p);
		var c = 1.;
		var inten = .0045;
		for (n in 0...MAX_ITER) {
			var t:Float = time * (1 - (3.5 / float(n + int(1))));
			i = p + vec2(cos(t - i.x) + sin(t + i.y), sin(t - i.y) + cos(1.5 * t + i.x));
			c += 1.0 / length(vec2(p.x / (cos(i.x + t) / inten), p.y / (cos(i.y + t) / inten)));
		}
		c /= float(MAX_ITER);
		c = 1.17 - pow(c, 1.4);
		var tex:Vec4 = texture2D(openfl_Texture, uv);
		var colour:Vec3 = vec3(pow(abs(c), 20.0));
		colour = clamp(colour + vec3(0.0, 0.0, .0), 0.0, tex.a);
		// 混合波光
		var alpha:Float = c * tex[3];
		tex[0] = tex[0] + colour[0] * alpha;
		tex[1] = tex[1] + colour[1] * alpha;
		tex[2] = tex[2] + colour[2] * alpha;
		gl_FragColor = tex + color * tex;
	}

	public function new(speed:Float = 1) {
		super();
		this.setFrameEvent(true);
		this.speed = speed;
	}

	override function onFrame() {
		super.onFrame();
		if (this.u_speed.value == null) {
			this.u_speed.value = [0];
		}
		this.u_speed.value[0] += 1 / 60 * speed;
	}
}
```

**Comment by rainyt** [comment]
It is the Shader implementation at the bottom of OpenFL, so it can be used in WebGL and OpenGL (C++).

**Comment by nanjizal** [comment]
rainyt

I am currently using this on WebGL ( hyperkitGL ).
gl.drawArrays( GL.TRIANGLES, 0, Std.int( ( end - start ) * 3 ) );
https://github.com/nanjizal/hyperKitGL/blob/main/src/hyperKitGL/PlyMix.js.hx#L209

But I think OpenFL does not use GL.TRIANGLE, I need separate independant control of each triangle so I can draw curved corners with triangles, does your example do this, not sure.

So for instance I am using triangles to create the curved corners of the textured star:
https://trilateralx.github.io/HyperKitGLsamples/src/hyperkitGLsamples/basic/index.html

Currently my engine allow control of the uv of each corner of each triangle.

I have a simple color test on Lime ( textures not yet implemented for lime ), so in theory could be mixable with OpenFL.
https://trilateralx.github.io/TrilateralSamples/lime/Atriangle/Export/html5/bin/index.html

It's using my kitGL which does not yet have texture, hyperKitGL is more advanced version just for webgl, with dsHelper structures mixed in.
https://github.com/nanjizal/kitGL/blob/master/src/kitGL/glLime/Ply.hx#L52

I have a abstract type math library 'geom', but mainly I implement the bare minimum and in trilateral3 and hyperkitGL I normally can do simple stuff without it, and just implement basic matrix muliplication minimum.

Currently the framework in trilateral3 is decoupled from array input structures, but leaning towards a interleaved data structure ( moved to Array<Float> because it's lighter to modify size on the fly than Float32Array ).

https://github.com/nanjizal/hyperKitGL/blob/main/src/hyperKitGL/io/ArrayColorTrianglesUV.hx

I am just drawing direct onto the data structure, and passing the data structure to the shader, so position, color, uv are defined for each corner a,b,c  something like this:
ax,ay,az,ared,ablue,agreen,aalpha
,au,av,bx,by,bz,bred,bblue,bgreen,balpha
,bu,bv,cy,cz,cred,cblue,cgreen,calpha,cu,cv

So there is one conversion from Array to Float32Array but mostly just working direct on the data structures.

This approach allows me to texture any shape much like 3d, and I can transfer shapes to 3D.  But I think I can't use your approach because I don't think you allow separate control of each uv triangle corner, but maybe I am wrong?

Would be nice if your library makes it easy to target OpenFL with trilateral3, but not really sure..

**Comment by rainyt** [comment]
Hello, the current openfl-glsl library is only compatible with DisplayObjectShader shader rendering, while providing the ability to translate GLSL. And the triangle library you mentioned seems to be an extended function, combined with OpenFL, this may not be solved by openfl-glsl. But if you want to use Haxe to write extended GLSL, there will be support in the future: For example, you can customize uv parameters, access them in Haxe, and then generate GLSL; but the implementation of extended parameters still needs to rely on your own implementation, because openfl-glsl Just did the work of translating GLSL. Hope to help you.

**Comment by nanjizal** [comment]
thanks for getting back to me.
