### ISSUE TITLE
what if i wanted to use #version 330 core 

### ISSUE THREAD

**Issue by JonnycatMeow** [rainyt/openfl-glsl#2]
the core version allows us mac users to use certain shaders that have uvec or other functions

**Comment by rainyt** [comment]
Hello, the current version does not support version definition, but I submitted a git version but did not test it.

```haxe
@:version("300 core")
class XXXShader extends OpenflShader {}
```

**Comment by rainyt** [comment]
You can try updating to the git version and then adding metadata to define the version number.`@:version("300 core")`

**Comment by JonnycatMeow** [comment]
oh ok i will try that

**Comment by JonnycatMeow** [comment]
![Screen Shot 2024-02-23 at 6 04 05 PM](https://github.com/rainyt/openfl-glsl/assets/107599365/0cf04d1a-79c5-4916-a065-c491827143e2)

**Comment by JonnycatMeow** [comment]
i used your openfl glsl samples https://github.com/rainyt/openfl-glsl-samples

**Comment by JonnycatMeow** [comment]
![Screen Shot 2024-02-23 at 6 35 23 PM](https://github.com/rainyt/openfl-glsl/assets/107599365/eb631a29-9f96-4a64-99e3-550c5e4702ef)

**Comment by rainyt** [comment]
Use @:version("300")?

**Comment by JonnycatMeow** [comment]
the 300 dosen't work for macos the only thing that works is 120 and lower

**Comment by rainyt** [comment]
Perhaps it is not supported, and it is rarely necessary to modify it.
